export const pageOrder = [
    '/',
    '/slides/intro',
    '/slides/intro/navn',
    '/slides/intro/origin',
    '/slides/intro/origin-2',
    '/slides/intro/svelte3',
    '/slides/intro/svelteKit',
    '/slides/compiler/landing',
    '/slides/compiler/list',
    '/slides/compiler/image',
    '/slides/framework/landing',
    '/slides/framework/list',
    '/slides/framework/image',
    '',
    '',
]